const {
    REDDIT_CLONE_DATABASE_HOST,
    REDDIT_CLONE_DATABASE_PORT,
    REDDIT_CLONE_DATABASE_NAME,
    REDDIT_CLONE_DATABASE_PASSWORD,
    REDDIT_CLONE_DATABASE_USER
} = process.env

export default {
    REDDIT_CLONE_DATABASE_NAME,
    REDDIT_CLONE_DATABASE_HOST,
    REDDIT_CLONE_DATABASE_PORT,
    REDDIT_CLONE_DATABASE_PASSWORD,
    REDDIT_CLONE_DATABASE_USER
}